spring:
  datasource:
    url: jdbc:mysql://192.168.205.10:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    hikari:
      username: root
      password: 1124chanshiyu
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.205.10
    port: 6379
    password:
    timeout: 15000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# swagger 配置
swagger:
  title: 時雨の接口文档
  description: 测试用 Api 接口
  version: 1.0.0
  base-package: com.chanshiyu.controller