server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/shiyu?nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    hikari:
      username: root
      password: 1124chanshiyu
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chanshiyu.pojo
swagger:
  title: 時雨の接口文档
  description: 测试用 Api 接口
  version: 1.0.0
  base-package: com.chanshiyu.controller
