server:
  port: 8090
############################################################
#
# 配置数据源相关
#
############################################################
spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/shiyu?nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    hikari:
      username: root
      password: 1124chanshiyu
      driver-class-name: com.mysql.cj.jdbc.Driver
  lettuce:
    database: 0
    host: ${redis.address}
    port: 6379
    password:
    timeout: 15000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chanshiyu.pojo
############################################################
#
# swagger 配置
#
############################################################
swagger:
  title: 時雨の接口文档
  description: 测试用 Api 接口
  version: 1.0.0
  base-package: com.chanshiyu.controller
############################################################
#
# fdfs 配置
#
############################################################
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.205.10:22122
############################################################
#
# disruptor
#
############################################################
# 1024 x 1024
disruptor:
  buffer:
    size: 1048576
