spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      uri: https://github.com/chanshiyucx/spring-cloud-config-client.git
      name: config-client
      label: master
      profile: dev

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/